name:                aoc
version:             0.1.0.0
github:              "githubuser/aoc"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/aoc#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- transformers
- fgl
- MemoTrie
- heap
- hashable
- unordered-containers
- astar
- text

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-orphans

library:
  source-dirs: src

_day: &day
  source-dirs: app
  other-modules: []
  dependencies: [aoc]

executables:
  aoc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc

  d00:
    <<: *day
    main: d00.hs

  d01:
    <<: *day
    main: d01.hs

  d02:
    <<: *day
    main: d02.hs

  d03:
    <<: *day
    main: d03.hs

  d04:
    <<: *day
    main: d04.hs

  d05:
    <<: *day
    main: d05.hs

  d06:
    <<: *day
    main: d06.hs

  d07:
    <<: *day
    main: d07.hs

  d08:
    <<: *day
    main: d08.hs

  d09:
    <<: *day
    main: d09.hs

  d10:
    <<: *day
    main: d10.hs

  d11:
    <<: *day
    main: d11.hs

  d12:
    <<: *day
    main: d12.hs

  d13:
    <<: *day
    main: d13.hs

  d14:
    <<: *day
    main: d14.hs

  d15:
    <<: *day
    main: d15.hs

  d16:
    <<: *day
    main: d16.hs

  d17:
    <<: *day
    main: d17.hs

  d18:
    <<: *day
    main: d18.hs

  d19:
    <<: *day
    main: d19.hs

  d20:
    <<: *day
    main: d20.hs

  d21:
    <<: *day
    main: d21.hs

  d22:
    <<: *day
    main: d22.hs

  d23:
    <<: *day
    main: d23.hs

  d24:
    <<: *day
    main: d24.hs

  d25:
    <<: *day
    main: d25.hs

  y2019d24:
    <<: *day
    main: y2019d24.hs


tests:
  aoc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc
